info:
  component: Turbine
spring:
  application:
    name: turbine

server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

turbine:
  appConfig: order-service,catalog-service
  clusterNameExpression: "'default'"
  combine-host-port: true #this allow Turbine multiple processes per host

