zuul:
  routes:
    resource:
      path: /order/**
      sensitiveHeaders:
      url: http://localhost:8083
    auth:
      path: /auth/**
      sensitiveHeaders:
      url: http://localhost:9999
    registry:
      path: /registry/**
      sensitiveHeaders:
      url: http://localhost:8761
    eurekaRes:
      path: /eureka/**
      sensitiveHeaders:
      url: http://localhost:8761/eureka
    catalog:
      path: /catalog/**
      sensitiveHeaders:
      url: http://localhost:8091

spring:
  application:
    name: zuul-gateway

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG