zuul:
  routes:
    resource:
      path: /order/**
      sensitiveHeaders:
      url: http://${order.host:localhost}:${order.port:8083}
    auth:
      path: /auth/**
      sensitiveHeaders:
      url: http://${auth.host:localhost}:${auth.port:9999}
    registry:
      path: /registry/**
      sensitiveHeaders:
      url: http://${eureka.host:localhost}:${eureka.port:8761}
    eurekaRes:
      path: /eureka/**
      sensitiveHeaders:
      url: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    catalog:
      path: /catalog/**
      sensitiveHeaders:
      url: http://${catalog.host:localhost}:${catalog.port:8091}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: zuul-gateway

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG