server:
  port: 8083

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: order-service